### ISSUE TITLE
JWT authentication engine mount can not be created if OIDCCredentials.secret is not set

### ISSUE THREAD

**Issue by snakebyte91** [redhat-cop/vault-config-operator#165]
If `OIDCCredentials.secret.name` is not specified the JWT authentication engine mount can not be configured. I get an error message like "no meanings found for secret".

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: gitlab
spec:
  authentication:
    path: kubernetes
    role: my-policy
    serviceAccount:
      name: my-sa
  connection:
    address: 'https://vault.example.com:8200'
  boundIssuer: gitlab.example.com
  JWKSURL: https://gitlab.example.com/-/jwks
  path: vault-config-operator/jwt
```

**Comment by erlisb** [comment]
@snakebyte91 I guess you get the following error: 

```
 {"controller": "jwtoidcauthengineconfig", "controllerGroup": "redhatcop.redhat.io", 
 "controllerKind": "JWTOIDCAuthEngineConfig", "JWTOIDCAuthEngineConfig": {"name":"gitlab","namespace":"vault-admin"}, 
 "namespace": "vault-admin", "name": "gitlab", "reconcileID": "651f4a79-3273-4e60-9325-b7b1da0156b6", 
 "error": "no means of retrieving a secret was specified"}
```

I applied a small [fix#165](https://github.com/redhat-cop/vault-config-operator/pull/167)

@raffaelespazzoli, what do you think ?

**Comment by snakebyte91** [comment]
@snakebyte91 Yes, I got this error.

**Comment by erlisb** [comment]
@snakebyte91 this should be fixed with the current release.
Can you check it and close this issue ?

**Comment by snakebyte91** [comment]
@erlisb I still get the error `no means of retrieving a secret was specified`

Vault config operator version: v0.8.17

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: gitlab
spec:
  authentication:
    path: kubernetes
    role: policy-vault-config-operator
    serviceAccount:
      name: controller-manager
  connection:
    address: 'https://vault.example.com:8200'
  boundIssuer: https://git.example.com.de
  JWKSURL: https://git.example.com/-/jwks
  path: jwt
```

**Comment by erlisb** [comment]
@snakebyte91 are you sure you are using the latest VCO release or if you upgraded to the lastest CRD versions ? 

I just tried your config and I get a different error :

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: AuthEngineMount
metadata:
  name: gitlab-jwt
spec:
  authentication: 
    path: kubernetes
    role: vault-admin
  type: oidc
  path: jwt
```

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: gitlab
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: default
  boundIssuer: https://git.example.com.de
  JWKSURL: https://git.example.com/-/jwks
  path: jwt/gitlab-jwt
```

error: 

`1.6910676757404606e+09  ERROR   unable to create/update vault resource  {"controller": "jwtoidcauthengineconfig", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "JWTOIDCAuthEngineConfig", "JWTOIDCAuthEngineConfig": {"name":"gitlab","namespace":"vault-admin"}, "namespace": "vault-admin", "name": "gitlab", "reconcileID": "43c5ec1b-51c6-4490-aa60-de0fb6eb2e91", "instance": {"apiVersion": "redhatcop.redhat.io/v1alpha1", "kind": "JWTOIDCAuthEngineConfig", "namespace": "vault-admin", "name": "gitlab"}, "error": "Error making API request.\n\nURL: PUT https://vault.vault.svc.cluster.local:8200/v1/auth/jwt/gitlab-jwt/config\nCode: 400. Errors:\n\n* error checking jwks URL"}`

which is expected, since JWKSURL is a non-existing one.

Can you recheck ?

**Comment by erlisb** [comment]
@raffaelespazzoli can we close this, as there is no feedback from the OP, for more than 3 weeks.

**Comment by dabelenda** [comment]
Hello,

I am hitting this issue with operator version 0.8.25 (deployed in OCP4) and trying to configure gitlab-ci to access vault as documented here: https://docs.gitlab.com/ee/ci/examples/authenticating-with-hashicorp-vault/

Note that since gitlab-ci is using a ID-token there is no clientid and client-secret to use. To configure vault to validate ID-tokens you do not specify the fields (I tried without vault-config-operator and it works).

Not setting the `OIDCCredentials` field I get a `LastReconcileCycleFailed` with message "no means of retrieving a secret was specified".

And in the logs of the operator I only have:
```
2024-01-22T14:30:57Z DEBUG reconcile {"controller": "jwtoidcauthengineconfig", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "JWTOIDCAuthEngineConfig", "JWTOIDCAuthEngineConfig": {"name":"gitlab-oidc-config","namespace":"vault-config-operator"}, "namespace": "vault-config-operator", "name": "gitlab-oidc-config", "reconcileID": "4c94d7b6-57d2-4892-abd4-c119ea6207c4", "instance": {"apiVersion": "redhatcop.redhat.io/v1alpha1", "kind": "JWTOIDCAuthEngineConfig", "namespace": "vault-config-operator", "name": "gitlab-oidc-config"}}
2024-01-22T14:30:57Z ERROR unable to prepare internal values {"controller": "jwtoidcauthengineconfig", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "JWTOIDCAuthEngineConfig", "JWTOIDCAuthEngineConfig": {"name":"gitlab-oidc-config","namespace":"vault-config-operator"}, "namespace": "vault-config-operator", "name": "gitlab-oidc-config", "reconcileID": "4c94d7b6-57d2-4892-abd4-c119ea6207c4", "instance": {"apiVersion": "redhatcop.redhat.io/v1alpha1", "kind": "JWTOIDCAuthEngineConfig", "namespace": "vault-config-operator", "name": "gitlab-oidc-config"}, "error": "no means of retrieving a secret was specified"}
github.com/redhat-cop/vault-config-operator/controllers/vaultresourcecontroller.(*VaultResource).manageReconcileLogic
/home/runner/work/vault-config-operator/vault-config-operator/controllers/vaultresourcecontroller/vaultresourcereconciler.go:95
github.com/redhat-cop/vault-config-operator/controllers/vaultresourcecontroller.(*VaultResource).Reconcile
/home/runner/work/vault-config-operator/vault-config-operator/controllers/vaultresourcecontroller/vaultresourcereconciler.go:65
github.com/redhat-cop/vault-config-operator/controllers.(*JWTOIDCAuthEngineConfigReconciler).Reconcile
/home/runner/work/vault-config-operator/vault-config-operator/controllers/jwtoidcauthengineconfig_controller.go:80
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226
2024-01-22T14:30:57Z ERROR unable to complete reconcile logic {"controller": "jwtoidcauthengineconfig", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "JWTOIDCAuthEngineConfig", "JWTOIDCAuthEngineConfig": {"name":"gitlab-oidc-config","namespace":"vault-config-operator"}, "namespace": "vault-config-operator", "name": "gitlab-oidc-config", "reconcileID": "4c94d7b6-57d2-4892-abd4-c119ea6207c4", "instance": {"apiVersion": "redhatcop.redhat.io/v1alpha1", "kind": "JWTOIDCAuthEngineConfig", "namespace": "vault-config-operator", "name": "gitlab-oidc-config"}, "error": "no means of retrieving a secret was specified"}
github.com/redhat-cop/vault-config-operator/controllers/vaultresourcecontroller.(*VaultResource).Reconcile
/home/runner/work/vault-config-operator/vault-config-operator/controllers/vaultresourcecontroller/vaultresourcereconciler.go:67
github.com/redhat-cop/vault-config-operator/controllers.(*JWTOIDCAuthEngineConfigReconciler).Reconcile
/home/runner/work/vault-config-operator/vault-config-operator/controllers/jwtoidcauthengineconfig_controller.go:80
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226
2024-01-22T14:30:57Z DEBUG events no means of retrieving a secret was specified {"type": "Warning", "object": {"kind":"JWTOIDCAuthEngineConfig","namespace":"vault-config-operator","name":"gitlab-oidc-config","uid":"b412ea66-5990-4589-b301-d0e3dfef3205","apiVersion":"redhatcop.redhat.io/v1alpha1","resourceVersion":"88217988"}, "reason": "ProcessingError"}
2024-01-22T14:30:57Z ERROR Reconciler error {"controller": "jwtoidcauthengineconfig", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "JWTOIDCAuthEngineConfig", "JWTOIDCAuthEngineConfig": {"name":"gitlab-oidc-config","namespace":"vault-config-operator"}, "namespace": "vault-config-operator", "name": "gitlab-oidc-config", "reconcileID": "4c94d7b6-57d2-4892-abd4-c119ea6207c4", "error": "no means of retrieving a secret was specified"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226
2024-01-22T14:33:05Z DEBUG controllers.VaultSecret Sync VaultSecret {"namespacedName": "vault-config-operator/gitlab-vault-auth-secret"}
```

**Comment by dabelenda** [comment]
Oh this is interesting: during the process of testing I created the CR with the field `OIDCCredentials` and then removed it.
Apparently if creating directly the CR without the `OIDCCredentials` field, it works.
